# add commit-msg hook type for commit message checks
default_install_hook_types:
  - pre-commit
  - commit-msg

# majority of hooks run only at pre-commit stage
default_stages:
  - pre-commit

default_language_version:
  python: python3.11


repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.280
    hooks:
      - id: ruff
        args:
          - "--fix"
          - "--exit-non-zero-on-fix"
        # exclude templated files and directories which cannot be parsed
        exclude: "{{ cookiecutter.__project_slug }}/.*"

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        # exclude templated files and directories which cannot be parsed
        exclude: "{{ cookiecutter.__project_slug }}/_features/"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        # exclude templated files and directories which cannot be parsed
        exclude: "{{ cookiecutter.__project_slug }}/"

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.22.0
    hooks:
      - id: check-github-actions
      - id: check-gitlab-ci

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.5.2
    hooks:
      - id: commitizen
