[tool.mypy]
ignore_missing_imports = true
exclude = [
    ".*conftest.py",
    ".*/tests/.*",
]

[tool.pytest.ini_options]
addopts = [
    "-ra",  # show summary for all except passed tests
    "-q",  # quiet
    "--strict-markers",  # require custom markers to be listed in config
]
testpaths = [
    "tests"
]

[tool.commitizen]
name = "cz_customize"

[tool.commitizen.customize]
message_template = """
{{title}}
{%- if description %}

{{ description }}
{%- endif %}
"""
example = """
add the shiny new feature

this feature increases shininess of the project
"""
schema = """
<title>

[optional description]
"""
schema_pattern = "^(.+)(\\n\\n.+)?$"
info = """
Commit message rules:
- commit message must not be empty
- if description is provided, it must be separated from title with a single blank line

Run "cz schema" to view commit message template.
"""

[[tool.commitizen.customize.questions]]
type = "input"
name = "title"
message = "Commit title: "

[[tool.commitizen.customize.questions]]
type = "input"
name = "description"
message = "Commit description: "
default = ""

[tool.ruff]
extend-exclude = [
    "tests",  # tests don't need to meet the requirements for production code
    "conftest.py",  # tests don't need to meet the requirements for production code
]
force-exclude = true # honor exclude config when files are passed to CLI with pre-commit
target-version = "py311"
select = [
    "ALL",  # majority1 of builtin rules are useful. specific list would be too large
]
ignore = [
    "D203",    # conflicts with D211, prefer no blank line before class docstring
    "D212",    # conflicts with D213, prefer docstring summary on the second line
    "EM",      # small clutter in exception trace doesn't justify redundant variable
    "TRY003",  # actually verifies the same thing as EM, ignore as well
    "ANN",     # mypy is used as type checker, this would overlap with it
]

[tool.ruff.flake8-bugbear]
extend-immutable-calls = [
    "fastapi.Depends", # Depends is immutable and is safe to whitelist against B008
]
