[tool.mypy]
ignore_missing_imports = true
exclude = [
    ".*conftest.py",
    ".*/tests/.*",
]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = [
    "-ra",  # show summary for all except passed tests
    "-q",  # quiet
    "--strict-markers",  # require custom markers to be listed in config
]
testpaths = [
    "tests"
]

[tool.commitizen]
name = "cz_customize"

[tool.commitizen.customize]
message_template = """
{{title}}
{%- if description %}

{{ description }}
{%- endif %}
"""
example = """
add the shiny new feature

this feature increases shininess of the project
"""
schema = """
<title>

[optional description]
"""
schema_pattern = "^(.+)(\\n\\n.+)?$"
info = """
Commit message rules:
- commit message must not be empty
- if description is provided, it must be separated from title with a single blank line

Run "cz schema" to view commit message template.
"""

[[tool.commitizen.customize.questions]]
type = "input"
name = "title"
message = "Commit title: "

[[tool.commitizen.customize.questions]]
type = "input"
name = "description"
message = "Commit description: "
default = ""
