[tool.mypy]
ignore_missing_imports = true
exclude = [
    ".*conftest.py",
    ".*/tests/.*",
]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = [
    "-ra",  # show summary for all except passed tests
    "-q",  # quiet
    "--strict-markers",  # require custom markers to be listed in config
]
testpaths = [
    "tests"
]
