on: deployment

name: Production

jobs:
  deploy-production:
    if: github.event.deployment.ref == 'main' && github.event.deployment.environment == 'production'

    runs-on: ubuntu-latest
    container: python:{{ cookiecutter.python_version }}-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v2
