on: push

name: Code QA

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    container: python:{{ cookiecutter.python_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install required packages
        run: |
          pip install -q pre-commit pipenv
          pre-commit install --install-hooks

      - name: Run code QA checks
        run: |
          pipenv run codeqa

  unit-tests:
    runs-on: ubuntu-latest
    container: python:{{ cookiecutter.python_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install required packages
        run: |
          pip install -q pipenv
          pipenv install -d --system --deploy

      - name: Run unit tests
        run: |
          pipenv run test_cov
