on: push

name: Code QA

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    container: docker:24.0.2-git
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fill environment variables
        run: cp .env.template .env

      - name: Run code QA tools
        run: docker compose run --build app pipenv run pre-commit run --all-files

  unit-tests:
    runs-on: ubuntu-latest
    image: docker:24.0.2-git

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # this fixes git permissions issue, see https://github.com/actions/checkout/issues/1048
      - name: Resolve permissions issue for repo directory
        run: "git config --system --add safe.directory ${GITHUB_WORKSPACE}"

      - name: Fill environment variables
        run: cp .env.template .env

      - name: Run tests
        run: docker compose run --build app pipenv run test_cov
