# add commit-msg hook type for commit message checks
default_install_hook_types:
  - pre-commit
  - commit-msg

# majority of hooks run only at pre-commit stage
default_stages:
  - pre-commit

default_language_version:
  python: python{{ cookiecutter.python_version }}

repos:

# ----- Python

  - repo: https://github.com/pycqa/isort
    rev: {{ cookiecutter._isort_version }}
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    # The `refs/tags/<tag>:refs/tags/<tag>` is needed for black's
    # required-version to work. See https://github.com/psf/black/issues/2493
    rev: 'refs/tags/{{ cookiecutter._black_version }}:refs/tags/{{ cookiecutter._black_version }}'
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: {{ cookiecutter._flake8_version }}
    hooks:
      - id: flake8

  # use local system hook instead of pre-commit mirror (uses isolated virtualenv)
  # to avoid copying typed dependencies to additional_dependencies
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        description: 'Python type checker'
        'types_or':
          - python
          - pyi
        language: system
        entry: mypy

        # the hook runs noticeably faster with single process
        require_serial: true

        # without this option, pre-commit passes every file as command line argument.
        # this breaks mypy exclude configuration, because mypy ignores it for files
        # passed this way.
        # this option disables advantages of pre-commit file discovery and slows down
        # the hook but is still better than copying exclude configuration here.
        # see discussion of the same issue in black formatter for additional context:
        # https://github.com/psf/black/issues/438
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: name-tests-test
      - id: debug-statements

  - repo: https://github.com/d-ryzhykau/pipenv-lock-pre-commit
    rev: 0.5.0
    hooks:
      - id: pipenv-verify

{% if cookiecutter.orm == 'SQLAlchemy' %}
# ----- Database

  - repo: https://github.com/sbdchd/squawk
    rev: v0.24.0
    hooks:
      - id: squawk
        entry: pipenv run lint-migrations
        pass_filenames: false
        files: {{cookiecutter.__project_slug}}/database/migrations/versions

  - repo: local
    hooks:
      - id: alembic-check
        name: alembic-check
        description: 'Check missing Alembic migrations'
        entry: pipenv run check-missing-migrations
        pass_filenames: false
        types:
          - python
        language: python
{%- endif %}

# ----- Non-Python syntax checks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-xml
{% if cookiecutter.ci_platform %}
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.22.0
    hooks:
      {%- if cookiecutter.ci_platform == 'GitHub Actions' %}
      - id: check-github-workflows
      {%- elif cookiecutter.ci_platform == 'GitLab CI' %}
      - id: check-gitlab-ci
      {%- endif %}
{%- endif %}

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v6.31.0
    hooks:
      - id: cspell
        args:
          - "--no-summary"
          - "--no-progress"
          - "--show-context"
          - "--cache"
        # the hook runs noticeably faster with single process
        require_serial: true

      # A hook to spellcheck file paths, because cspell doesn't have such option.
      # A separate hook run allows to make the check explicit in the output.
      # Therefore, it is preferable to reuse of the hook above, even at the cost
      # of running cspell twice.
      - id: cspell
        name: cspell-file-paths
        # use pipfile wrapper script because pre-commit always passes file list as the
        # last part of the command
        entry: pipenv run spellcheck-file-paths
        # disable built-in arguments, wrapper script expects file names only
        args: []
        # the hook runs noticeably faster with single process
        require_serial: true

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.5.2
    hooks:
      - id: commitizen

# ----- Secrets detection

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-private-key

# ----- Formatting

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--no-ensure-ascii"

# ----- Project structure

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-symlinks
      - id: forbid-submodules
      - id: check-added-large-files
