default_language_version:
  python: python{{ cookiecutter.python_version }}

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: {{ cookiecutter._black_version }}
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v{{ cookiecutter._mypy_version }}
    hooks:
      - id: mypy
