[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "-ra -q --strict-markers"

[tool.coverage.run]
branch = true
source = [
    "./{{ cookiecutter.__project_slug }}/",
]
omit = [
    "*/tests/*",
]
