[tool.black]
target-version = ["py{{ cookiecutter.python_version | replace('.', '') }}"]
required-version = "{{ cookiecutter._black_version }}"
quiet = true

[tool.mypy]
strict = true

# need to check type hints in the project code only,
# so suppress warnings about missing annotations in 3rd party code
ignore_missing_imports = true

files = [
    "./{{ cookiecutter.__project_slug }}/",
]
exclude = [
    ".*conftest.py",
    ".*/tests/.*",
]
{% if cookiecutter.web_framework == 'FastAPI' %}
plugins = [
    "pydantic.mypy",
]
{%- endif %}

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = [
    "-ra",  # show summary for all except passed tests
    "-q",  # quiet
    "--strict-markers",  # require custom markers to be listed in config
    # skip fully covered files in coverage report
    "--cov-report=term-missing:skip-covered",
]

[tool.coverage.run]
branch = true
source = [
    "./{{ cookiecutter.__project_slug }}/",
]
omit = [
    "./*conftest.py",
    "./*tests/*",
]

[tool.coverage.report]
fail_under = 0
