[tool.black]
target-version = ["py{{ cookiecutter.python_version | replace('.', '') }}"]
required-version = "{{ cookiecutter._black_version }}"
quiet = true

[tool.mypy]
strict = true

# need to check type hints in the project code only,
# so suppress warnings about missing annotations in 3rd party code
ignore_missing_imports = true

files = [
    "./{{ cookiecutter.__project_slug }}/",
]
exclude = [
    ".*conftest.py",
    ".*/tests/.*",
]
{% if cookiecutter.web_framework == 'FastAPI' %}
plugins = [
    "pydantic.mypy",
]
{%- endif %}

[tool.pytest.ini_options]
addopts = [
    "-ra",  # show summary for all except passed tests
    "-q",  # quiet
    "--strict-markers",  # require custom markers to be listed in config
    # skip fully covered files in coverage report
    "--cov-report=term-missing:skip-covered",
]

[tool.coverage.run]
branch = true
source = [
    "./{{ cookiecutter.__project_slug }}/",
]
omit = [
    "./*conftest.py",
    "./*tests/*",
]

[tool.coverage.report]
fail_under = 0

[tool.commitizen]
name = "cz_customize"

[tool.commitizen.customize]
message_template = {% raw %}"""
{{title}}
{%- if description %}

{{ description }}
{%- endif %}
"""
{%- endraw %}
example = """
add the shiny new feature

this feature increases shininess of the project
"""
schema = """
<title>

[optional description]
"""
schema_pattern = "^(.+)(\\n\\n.+)?$"
info = """
Commit message rules:
- commit message must not be empty
- if description is provided, it must be separated from title with a single blank line

Run "cz schema" to view commit message template.
"""

[[tool.commitizen.customize.questions]]
type = "input"
name = "title"
message = "Commit title: "

[[tool.commitizen.customize.questions]]
type = "input"
name = "description"
message = "Commit description: "
default = ""

[tool.ruff]
extend-exclude = [
    "tests",  # tests don't need to meet the requirements for production code
    "conftest.py",  # tests don't need to meet the requirements for production code
]
force-exclude = true # honor exclude config when files are passed to CLI with pre-commit
target-version = "py{{ cookiecutter.python_version | replace('.', '') }}"
select = [
    "ALL",  # majority of builtin rules are useful. specific list would be too large
]
ignore = [
    "D203",    # conflicts with D211, prefer no blank line before class docstring
    "D212",    # conflicts with D213, prefer docstring summary on the second line
    "EM",      # small clutter in exception trace doesn't justify redundant variable
    "TRY003",  # actually verifies the same thing as EM, ignore as well
    "ANN",     # mypy is used as type checker, this would overlap with it
]

[tool.ruff.flake8-bugbear]
extend-immutable-calls = [
    "fastapi.Depends", # Depends is immutable and is safe to whitelist against B008
]
