on: push

name: Code QA

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # this fixes git permissions issue, see https://github.com/actions/checkout/issues/1048
      - name: Resolve permissions issue for repo directory
        run: "git config --system --add safe.directory ${GITHUB_WORKSPACE}"

      - name: Install pre-commit
        run: |
          pip install -q pre-commit pipenv
          pre-commit install

      - name: Run code QA tools from pre-commit hooks
        run: |
          pipenv run codeqa

  tests:
    runs-on: ubuntu-latest
    container: python:3.10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install required packages
        run: |
          pip install -q pipenv
          pipenv install -d --system --deploy

      - name: Run tests
        run: |
          pipenv run test
