on: push

name: Code QA

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pre-commit
        run: |
          pip install -q pre-commit
          pre-commit install --install-hooks

      - name: Run code QA tools from pre-commit hooks
        run: |
          pre-commit run --all-files

  tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install required packages
        run: |
          pip install -q pipenv
          pipenv install -d --system --deploy

      - name: Run tests
        run: |
          pytest
