PYTHON_CONTAINER: &PYTHON_CONTAINER 'python:3.9-slim'

on: deployment

name: Production

jobs:
  deploy-production:
    if: github.event.deployment.ref == 'main' && github.event.deployment.environment == 'production'

    runs-on: ubuntu-latest
    container: *PYTHON_CONTAINER

    steps:
      - name: Checkout
        uses: actions/checkout@v2
